server:
  port: 8080
  mode: debug

redis:
  host: 47.93.186.33
  port: 6379
  password: "JdK"
  db: 11

mongodb:
  uri: "mongodb://adminUser:123@47.93.186.33:27017/"
  database: "intelli_dl_online_logo_dev"

log:
  level: "debug"
  format: "console"  # console 或 json
  output: "stdout"   # stdout 或文件路径
  directory: "D:/logs/intelli_dl_online_logo"
  filename: "app"
  max_size: 100      # MB
  max_age: 30        # 天
  max_backups: 10
  compress: false 

# 新增邮件配置
mail:
  host: smtp.example.com
  port: 587
  username: your-email@example.com
  password: your-password
  from_name: Your App Name 