server:
  port: 8080
  mode: release

redis:
  host: 47.93.186.33
  port: 6379
  password: "JdK"
  db: 1

mongodb:
  uri: "mongodb://adminUser:01@47.93.186.33:27017/"
  database: "intelli_dl_online_logo"

log:
  level: "info"
  format: "json"
  output: "file"
  directory: "/var/log/intelli_dl_online_logo/"
  filename: "app"
  max_size: 100
  max_age: 30
  max_backups: 10
  compress: true

# 新增邮件配置
mail:
  host: smtp.163.com
  port: 465
  username: intelli_dl@163.com
  password: 123456
  from_name: Intelli-dl-online-logo